### ISSUE TITLE
Location property doesn't appear

### ISSUE THREAD

**Issue by javierseixas** [jose-elias-alvarez/obsidian-geocoding-properties#2]
Hi! I use the map view plugin for geo referencing notes that have a location property in them.

Since the last update of Obsidian, the new location properties I add stopped being recognized as geo location (since Obsidian understands it as title/text). Because of that, I installed this plugin, expecting that a new location property will be available, so I will be able to select it and have the functionality again.

However, this behaviour doesn't occurs, no new location property appears. Do I understanding wrongly how this plugin works? 

Here's my configuration:

![Selection_178](https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/953900/1801363f-7b9c-41c6-8a23-5f2e37e15b1b)

Here's what I see from the note (no location tag can be selected):

![Selection_180](https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/953900/818e623e-abc8-4fef-89f7-81bb4d7b194d)

Thanks for your help, José Elías! :raised_hands:

**Comment by jose-elias-alvarez** [comment]
Apologies for the late reply. If I understand your question correctly: Obsidian has a limited set of property types that it recognizes, and to my knowledge it's not possible for plugins to contribute new types. 

This plugin uses the `list` property for location coordinates, which makes it compatible with [obsidian-leaflet](https://github.com/javalent/obsidian-leaflet). I'm not sure what behavior you were seeing before the update, but is this causing you any issues in usage?

**Comment by jose-elias-alvarez** [comment]
Closing this, but if you're still having problems feel free to open another issue.
