### ISSUE TITLE
Suddenly started getting 401 error

### ISSUE THREAD

**Issue by Kageetai** [jose-elias-alvarez/obsidian-geocoding-properties#3]
<img width="280" alt="Screenshot 2023-12-26 at 09 45 24" src="https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/1738309/c65573eb-c81f-4586-81f3-890fbe6ae279">

The above error suddenly started to appear when trying to fetch geocoding information as usual. Still worked some days ago. Only thing that changed is the update to `v1.5.3`.
No error messages seems to appear in the browsers console.

**Comment by jose-elias-alvarez** [comment]
Sorry for the delayed reply. Which provider are you using? The plugin is still working as expected for me with both Google Geocoding and Free Geocoding API.
