### ISSUE TITLE
FR: Add option or separate command to add frontmatter data automatically, without a user modal

### ISSUE THREAD

**Issue by evanharmon1** [jose-elias-alvarez/obsidian-geocoding-properties#6]
I really appreciate the dynamic logic of how the plugin adds data based on multiple possible frontmatter data. What would be perfect for my use case is an option or, ideally a separate command to apply the data without user interaction. E.g. I have a template that could change a note to a "location" note but it doesn't work quite right because of the user interaction.

**Comment by jose-elias-alvarez** [comment]
Added in 6d20714 and released in 1.2.1. Thanks!

**Comment by evanharmon1** [comment]
Works great! Thanks you!
