### ISSUE TITLE
`map_view_link` does not appear in frontmatter

### ISSUE THREAD

**Issue by Kageetai** [jose-elias-alvarez/obsidian-geocoding-properties#7]
Hey there,
thanks for the update with version 1.1.1, the `map_view_link` property seems to be a nice addition to work with map views.
Unfortunately, it doesn't show up for me when using it with the latest version:
![Screenshot 2024-02-29 at 10 51 28](https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/1738309/e4a8eb21-8e6c-4ebe-98bb-57690b7964f0)
Am I missing some setting or so?

**Comment by jose-elias-alvarez** [comment]
Did you make sure to enable the new property in the plugin's settings?

![Screenshot 2024-03-08 at 1 13 34 PM](https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/54108223/e777f900-1005-46d4-a787-956cffaa06bf)

**Comment by Kageetai** [comment]
I was looking for that before already, but I just don't have that line in the settings:

<img width="775" alt="Screenshot 2024-03-08 at 23 57 07" src="https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/1738309/fce45e09-0e9e-4d0b-bdde-ad11446a11f9">

**Comment by Kageetai** [comment]
Okay, I deleted the `data.json` file and deactivated and reactivated the plugin and then the missing setting was there. Could it be you only show the setting if it's present in the `data.json`?

**Comment by jose-elias-alvarez** [comment]
Hmm, it could be. I know another user had a similar issue that required them to reinstall the plugin. I might be doing something wrong on my end, so I'll see if other plugin authors have run into similar issues.

**Comment by jose-elias-alvarez** [comment]
There was an issue that made new properties invisible, which should be fixed by 5d76605. Thanks for the report!

**Comment by Kageetai** [comment]
Thanks, good catch. Maybe I should do the same for my own plugin 😅
