### ISSUE TITLE
Cannot access settings

### ISSUE THREAD

**Issue by sandervdvijver** [jose-elias-alvarez/obsidian-geocoding-properties#9]
Hello, I can successfully install the plugin, but can't access the settings (see screenshot).
I have tried restarting Obsidian, uninstalling, deleting and re-installing.
Obsidian version: Version 1.5.12

<img width="744" alt="image" src="https://github.com/jose-elias-alvarez/obsidian-geocoding-properties/assets/1092644/a784f195-c6f3-46ec-83a2-8d5917d292d5">

**Comment by jose-elias-alvarez** [comment]
Should be fixed in 2.0.2, can you try updating and let me know? If it's still not fixed can you [open the console](https://forum.obsidian.md/t/how-to-access-the-console/16703) and screenshot any error output there?

**Comment by sandervdvijver** [comment]
The update fixed it! Thanks 👍
